// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsY6PnNtHp_Md09urRBqx86EmCsI3B2o',
    appId: '1:153165204817:web:bf5f28edddebb32b971770',
    messagingSenderId: '153165204817',
    projectId: 'login-d57f5',
    authDomain: 'login-d57f5.firebaseapp.com',
    storageBucket: 'login-d57f5.appspot.com',
    measurementId: 'G-ES12SMJW8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDYFvAcmWpq4jTkjOnUO2Wh2CK4GEEZ4',
    appId: '1:153165204817:android:fa6f8741e0d4ab89971770',
    messagingSenderId: '153165204817',
    projectId: 'login-d57f5',
    storageBucket: 'login-d57f5.appspot.com',
  );
}
